### ISSUE TITLE
unable to start notary server

### ISSUE THREAD

**Issue by Rahul-github** [theupdateframework/notary#1262] opened 2017-11-10 18:07 UTC
Hello:

I'm following below steps to run Notary service but ending up with following errors
https://docs.docker.com/notary/running_a_service/#run-a-service-for-testing-or-development 

Can you please help me to fix this.
```
signer_1  | ./migrations/migrate.sh: line 63: migrate: not found
signer_1  | waiting for mysql://signer@tcp(mysql:3306)/notarysigner to come up.
server_1  | ./migrations/migrate.sh: line 63: migrate: not found
server_1  | waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
```

**Comment by Rahul-github** [comment] 2017-11-10 22:27
can anyone help me please

**Comment by ReidWeb** [comment] 2017-11-11 22:09
I am also getting the error 
```
waiting for mysql://server@tcp(mysql:3306)/notaryserver to come up.
```

**Comment by riyazdf** [comment] 2017-11-12 09:06
I am unable to reproduce this issue - could you please provide more logs from the database container or any other details?
In particular: are you deviating from `docker-compose up` in the freshly cloned repo?

Also, I don't think this should cause an issue but are you using the new repo path `theupdateframework/notary` instead of `docker/notary`?  I checked locally and it worked for both paths for me.

**Comment by Rahul-github** [comment] 2017-11-13 22:28
Somehow I manage to start but not able to do init seeing following error
```
ec2-user@mydockernotary:~/.notary$ notary -D init docker/ucp-controller
DEBU[0000] Using the following trust directory: /home/myhome/.docker/trust
DEBU[0000] Trusting 1 certs
ERRO[0000] could not reach https://mydockernotary.corp.com: Get https://mydockernotary.corp.com/v2/: x509: certificate is valid for *.com, *.*.com, example.com, *.dtr, *.*.dtr, not mydockernotary.corp.com
INFO[0000] continuing in offline mode
DEBU[0000] No yubikey found, using alternative key storage: no library found
DEBU[0000] No yubikey found, using alternative key storage: no library found
Root key found, using: cb91231dff5f8da9431cab0f18123dc28202c31a0fdca4ea3a3fc17af2655a9b
DEBU[0000] No yubikey found, using alternative key storage: no library found
Enter passphrase for root key with ID cb91231:
```
I'm not sure if i did something wrong while installation

```
ec2-user@mydockernotary:~/.notary$ docker ps | grep notary
ff7826d1910c        notary_server                    "/usr/bin/env sh -..."   About an hour ago   Up About an hour      0.0.0.0:4443->4443/tcp, 0.0.0.0:32772->8080/tcp                                   notary_server_1
13faf7082ded        notary_signer                    "/usr/bin/env sh -..."   About an hour ago   Up About an hour                                                                                        notary_signer_1
f75effa23f2c        mariadb:10.1.28                  "docker-entrypoint..."   About an hour ago   Up About an hour      3306/tcp                                                                          notary_mysql_1
3838a20e812c        docker/dtr-notary-signer:2.4.0   "/start.sh"              4 days ago          Up 32 minutes                                                                                           dtr-notary-signer-f77eb2435263
bac8876b7b54        docker/dtr-notary-server:2.4.0   "/start.sh"              4 days ago          Up 32 minutes                                                                                           dtr-notary-server-f77eb2435263
```
Please suggest what i have to do to resolve this issue

Thanks a lot for your help in advance!!

**Comment by Rahul-github** [comment] 2017-11-14 18:12
Any help please to fix this

**Comment by riyazdf** [comment] 2017-11-14 19:28
hi @Rahul-github, can you please help us with more information that we had asked for previously?  That would be very helpful.

> In particular: are you deviating from docker-compose up in the freshly cloned repo? Are you using the master branch or a specific commit?

Also: are you specifically using Notary within a Docker EE setup?  If so, Docker Support can help you.

**Comment by Rahul-github** [comment] 2017-11-14 20:22
Hello Riyaz:

I'm running evaluation license, no option for me to get support from support. looks like only you can help me out :) 

I cloned the repo from git clone https://github.com/docker/notary.git and ran docker compose, Initially, I was following instructions mentions in Gitbook[Yubikey Handbook].

**Comment by riyazdf** [comment] 2017-11-14 20:32
@Rahul-github: ok this information helps.  Docker EE includes a Notary server and signer by default, so you don't need to interact with the Notary source code at all.  The `docker/dtr-notary-signer:2.4.0` and `docker/dtr-notary-server:2.4.0` containers are already deployed for you.

The appropriate place to troubleshoot any additional Docker EE issues is the Docker forums here: https://forums.docker.com/c/docker-data-center

I'll close this issue and we can revisit any followups there.

**Closed by riyazdf** 2017-11-14 20:32 UTC
